name: CI
on: [pull_request]
jobs:
  Lint-Commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # we actually need "github.event.pull_request.commits + 1" commit
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup node.js
        uses: actions/setup-node@v2

      - name: Lint
        run: |
          FIRST_COMMIT_SHA=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" ${{ github.event.pull_request.commits_url }} | jq -r '.[0].sha')
          npm ci
          npx commitlint --from $FIRST_COMMIT_SHA^ --verbose

  Codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node.js
        uses: actions/setup-node@v2

      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          # token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          # files: ./coverage1.xml,./coverage2.xml # optional
          flags: unittests # optional
          # name: codecov-umbrella # optional
          # fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
