name: Lint Commit
on: [push]
jobs:
  Lint-Commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # we actually need "github.event.pull_request.commits + 1" commit
          fetch-depth: 0
      - uses: actions/setup-node@v2
      # or just "yarn" if you depend on "@commitlint/cli" already
      - run: yarn add @commitlint/cli
      - run: yarn run commitlint --from HEAD~${{ github.event.push.commits }} --to HEAD
